/**
 * 包内静态资源清单（构建时由 build.mjs 自动生成，勿手改）：
 * 示范音频 key：c-<卡牌id> / n-<街坊id>-<台词序号>；未列出的 key 播放时提示看粤拼跟读。
 * 第 3 章起的立绘/背景/音频放分包 resN（wx 端会先 loadSubpackage）。
 */
export const AUDIO_KEYS: ReadonlySet<string> = new Set<string>([
  "c-bou1waan4",
  "c-bungei",
  "c-cankau",
  "c-ceot1loeng4",
  "c-cing1jat6",
  "c-dang6jat6",
  "c-dangzan",
  "c-dim2soeng5",
  "c-doze",
  "c-gaaifong",
  "c-gaap3cin2",
  "c-gaapsi4",
  "c-gaau1bei2",
  "c-gaau2din6",
  "c-gaautin",
  "c-geido",
  "c-geidonim2",
  "c-gonsigan",
  "c-gwozaam",
  "c-haaci3je6",
  "c-hainei",
  "c-hei2caau2",
  "c-heobin",
  "c-hoisoeng",
  "c-hongloengfan",
  "c-houmei",
  "c-jam2caa4",
  "c-jau5je5",
  "c-jau5seoi1",
  "c-jungbatdaatung",
  "c-loengwai",
  "c-lokce",
  "c-lokcebin",
  "c-m4gam3ji3",
  "c-m4haai3",
  "c-maaidaan",
  "c-maangong",
  "c-maanmaan",
  "c-manlou",
  "c-meibaance",
  "c-mganjiu",
  "c-mgoi",
  "c-mgoibong",
  "c-mgoineoi",
  "c-mhaiban",
  "c-mhouji",
  "c-mingsan",
  "c-moumantai",
  "c-moungaangbei",
  "c-naaicaa",
  "c-ngaam1ngaam1",
  "c-peng",
  "c-pinji",
  "c-saamgodis",
  "c-saidin88",
  "c-saiseng",
  "c-sakdak1",
  "c-sengjat",
  "c-seoifai3",
  "c-siceigei",
  "c-sik1sin1",
  "c-tai2fan6",
  "c-tau4sin1",
  "c-tintoim4",
  "c-wonggok",
  "c-wunsoeng5",
  "c-zap1hou2",
  "c-zaubing",
  "c-zebou6syun1",
  "c-zing3geoi3",
  "c-zousan",
  "c-zyun3zing3",
  "c-zyunce",
  "c-zyunzuifaai",
  "n-auntie-0",
  "n-auntie-1",
  "n-auntie-2",
  "n-boss-0",
  "n-boss-1",
  "n-boss-2",
  "n-boss-3",
  "n-buscaptain-0",
  "n-buscaptain-1",
  "n-buscaptain-2",
  "n-buscaptain-3",
  "n-chair-0",
  "n-chair-1",
  "n-chair-2",
  "n-chair-3",
  "n-chief-0",
  "n-chief-1",
  "n-chief-2",
  "n-clerk-0",
  "n-clerk-1",
  "n-clerk-2",
  "n-director-0",
  "n-director-1",
  "n-director-2",
  "n-director-3",
  "n-faan-0",
  "n-faan-1",
  "n-faan-2",
  "n-grandpa-0",
  "n-grandpa-1",
  "n-grandpa-2",
  "n-kid-0",
  "n-kid-1",
  "n-kid-2",
  "n-landlady-0",
  "n-landlady-1",
  "n-landlady-2",
  "n-minibus-0",
  "n-minibus-1",
  "n-minibus-2",
  "n-mtrstaff-0",
  "n-mtrstaff-1",
  "n-mtrstaff-2",
  "n-neibour-0",
  "n-neibour-1",
  "n-neibour-2",
  "n-recap-0",
  "n-recap-1",
  "n-recap-2",
  "n-staff-0",
  "n-staff-1",
  "n-staff-2",
  "n-taxi-0",
  "n-taxi-1",
  "n-taxi-2",
  "n-waiter-0",
  "n-waiter-1",
  "n-waiter-2"
]);

const AUDIO_SUB: Record<string, string> = {
  "c-bou1waan4": "res3",
  "c-bungei": "res3",
  "c-cankau": "res3",
  "c-ceot1loeng4": "res4",
  "c-cing1jat6": "res3",
  "c-dang6jat6": "res4",
  "c-dim2soeng5": "res4",
  "c-gaap3cin2": "res3",
  "c-gaapsi4": "res4",
  "c-gaau1bei2": "res3",
  "c-gaau2din6": "res4",
  "c-gaautin": "res3",
  "c-geidonim2": "res4",
  "c-haaci3je6": "res3",
  "c-hei2caau2": "res4",
  "c-jam2caa4": "res3",
  "c-jau5je5": "res3",
  "c-jau5seoi1": "res4",
  "c-m4gam3ji3": "res4",
  "c-m4haai3": "res4",
  "c-mgoibong": "res3",
  "c-mgoineoi": "res4",
  "c-mingsan": "res4",
  "c-ngaam1ngaam1": "res3",
  "c-saiseng": "res3",
  "c-sakdak1": "res4",
  "c-seoifai3": "res3",
  "c-sik1sin1": "res4",
  "c-tai2fan6": "res4",
  "c-tau4sin1": "res3",
  "c-tintoim4": "res3",
  "c-wunsoeng5": "res4",
  "c-zap1hou2": "res3",
  "c-zebou6syun1": "res3",
  "c-zing3geoi3": "res4",
  "c-zyun3zing3": "res4",
  "n-chair-0": "res3",
  "n-chair-1": "res3",
  "n-chair-2": "res3",
  "n-chair-3": "res3",
  "n-chief-0": "res4",
  "n-chief-1": "res4",
  "n-chief-2": "res4",
  "n-clerk-0": "res4",
  "n-clerk-1": "res4",
  "n-clerk-2": "res4",
  "n-director-0": "res4",
  "n-director-1": "res4",
  "n-director-2": "res4",
  "n-director-3": "res4",
  "n-faan-0": "res3",
  "n-faan-1": "res3",
  "n-faan-2": "res3",
  "n-kid-0": "res3",
  "n-kid-1": "res3",
  "n-kid-2": "res3",
  "n-neibour-0": "res3",
  "n-neibour-1": "res3",
  "n-neibour-2": "res3",
  "n-staff-0": "res4",
  "n-staff-1": "res4",
  "n-staff-2": "res4"
};

const ASSET_SUB: Record<string, string> = {
  "neibour.png": "res3",
  "kid.png": "res3",
  "faan.png": "res3",
  "chair.png": "res3",
  "bg/rooftop.jpg": "res3",
  "staff.png": "res4",
  "clerk.png": "res4",
  "chief.png": "res4",
  "director.png": "res4",
  "doctor.png": "res5",
  "bg/clinic.jpg": "res5",
  "counter.png": "res5",
  "ticket.png": "res5",
  "yuen.png": "res5"
};

/** rel 形如 "street/auntie.png" 或 "street/bg/rooftop.jpg" */
export function assetPath(rel: string): string {
  const bare = rel.replace(/^street\//, "");
  const s = ASSET_SUB[bare];
  return s ? `${s}/${bare}` : rel;
}

export function audioPath(key: string): string | null {
  if (!AUDIO_KEYS.has(key)) return null;
  const s = AUDIO_SUB[key];
  return s ? `${s}/${key}.mp3` : `audio/street/${key}.mp3`;
}
