/**
 * P17 词海 · 幕1 扩容（骑楼长街）：寒暄问候 / 感谢道歉 / 买卖讲价 / 问路求助 / 数字时间。
 * 仅经 skillsFor 第五参 lexiconVersion=1 进入新战役卡池；旧局不可获取。
 * 粤拼为 LSHK 方案人工编写，待母语审校（P7 惯例）。
 */
import type { Skill } from "../../data";

export const P17_SKILLS_ACT1: Skill[] = [
  {
    id: "p17-nei5-hou2",
    name: "你好",
    phrase: "你好",
    alternatives: ["你好", "您好"],
    jyutping: "nei5 hou2",
    lesson: "打招呼的基本问候",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-daai6-gaa1-hou2",
    name: "大家好",
    phrase: "大家好",
    alternatives: ["大家好"],
    jyutping: "daai6 gaa1 hou2",
    lesson: "对一群人问好",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-hou2-noi6-mou5-gin3",
    name: "好耐冇见",
    phrase: "好耐冇见",
    alternatives: ["好耐冇见", "好耐冇見", "好久不见"],
    jyutping: "hou2 noi6 mou5 gin3",
    lesson: "好久不见",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-gan6-paai4-dim2-aa3",
    name: "近排点呀",
    phrase: "近排点呀",
    alternatives: ["近排点呀", "近排點呀"],
    jyutping: "gan6 paai4 dim2 aa3",
    lesson: "最近怎么样",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-gei2-hou2",
    name: "几好",
    phrase: "几好",
    alternatives: ["几好", "幾好", "挺好"],
    jyutping: "gei2 hou2",
    lesson: "还不错（答「近排点呀」）",
    type: "hybrid",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "造成 {power} 点伤害，并获得等量护甲。"
  },
  {
    id: "p17-m4-co3",
    name: "唔错",
    phrase: "唔错",
    alternatives: ["唔错", "唔錯", "不错"],
    jyutping: "m4 co3",
    lesson: "不错、挺好的",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-hai6-gam2-sin1",
    name: "系咁先",
    phrase: "系咁先",
    alternatives: ["系咁先", "係咁先", "先这样"],
    jyutping: "hai6 gam2 sin1",
    lesson: "先这样（告别语）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-dai6-jat6-gin3",
    name: "第日见",
    phrase: "第日见",
    alternatives: ["第日见", "改天见"],
    jyutping: "dai6 jat6 gin3",
    lesson: "改天再见",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-jat1-lou6-seon6-fung1",
    name: "一路顺风",
    phrase: "一路顺风",
    alternatives: ["一路顺风", "一路順風"],
    jyutping: "jat1 lou6 seon6 fung1",
    lesson: "送别祝福",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-m4-goi1-saai3",
    name: "唔该晒",
    phrase: "唔该晒",
    alternatives: ["唔该晒", "唔該曬", "太感谢了"],
    jyutping: "m4 goi1 saai3",
    lesson: "多谢帮忙（晒加强语气）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-taai3-maa4-faan4-nei5",
    name: "太麻烦你",
    phrase: "太麻烦你",
    alternatives: ["太麻烦你", "太麻煩你"],
    jyutping: "taai3 maa4 faan4 nei5",
    lesson: "给人添麻烦时的客套",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-deoi3-m4-zyu6",
    name: "对唔住",
    phrase: "对唔住",
    alternatives: ["对唔住", "對唔住", "对不起"],
    jyutping: "deoi3 m4 zyu6",
    lesson: "对不起（真心道歉）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-m4-gan2-jiu3",
    name: "唔紧要",
    phrase: "唔紧要",
    alternatives: ["唔紧要", "唔緊要", "没关系"],
    jyutping: "m4 gan2 jiu3",
    lesson: "没关系（回应道歉）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-mou5-so2-wai6",
    name: "冇所谓",
    phrase: "冇所谓",
    alternatives: ["冇所谓", "冇所謂", "无所谓"],
    jyutping: "mou5 so2 wai6",
    lesson: "无所谓、都行",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-m4-sai2-haak3-hei3",
    name: "唔使客气",
    phrase: "唔使客气",
    alternatives: ["唔使客气", "唔使客氣", "不客气"],
    jyutping: "m4 sai2 haak3 hei3",
    lesson: "别客气（回应道谢）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-jau5-sam1",
    name: "有心",
    phrase: "有心",
    alternatives: ["有心", "谢谢你有心"],
    jyutping: "jau5 sam1",
    lesson: "谢谢你的心意",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-sam1-ling5",
    name: "心领",
    phrase: "心领",
    alternatives: ["心领", "心領"],
    jyutping: "sam1 ling5",
    lesson: "心领（婉拒好意）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-taai3-gwai3-laa1",
    name: "太贵啦",
    phrase: "太贵啦",
    alternatives: ["太贵啦", "太貴啦", "太贵了"],
    jyutping: "taai3 gwai3 laa1",
    lesson: "嫌贵开场白",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-peng2-di1-laa1",
    name: "平啲啦",
    phrase: "平啲啦",
    alternatives: ["平啲啦", "便宜点"],
    jyutping: "peng2 di1 laa1",
    lesson: "便宜一点（讲价）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-jau5-mou5-zit3",
    name: "有冇折",
    phrase: "有冇折",
    alternatives: ["有冇折", "有没有折扣"],
    jyutping: "jau5 mou5 zit3",
    lesson: "有没有折扣",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-m4-maai5-laa3",
    name: "唔买喇",
    phrase: "唔买喇",
    alternatives: ["唔买喇", "唔買喇", "不买了"],
    jyutping: "m4 maai5 laa3",
    lesson: "不买了（转身就走）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-ngo5-jiu3-ni1-go3",
    name: "我要呢个",
    phrase: "我要呢个",
    alternatives: ["我要呢个", "我要這個", "我要这个"],
    jyutping: "ngo5 jiu3 ni1 go3",
    lesson: "我要这个（呢=这）",
    type: "hybrid",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "造成 {power} 点伤害，并获得等量护甲。"
  },
  {
    id: "p17-bei2-loeng5-go3-ngo5",
    name: "畀两个我",
    phrase: "畀两个我",
    alternatives: ["畀两个我", "畀兩個我", "给我两个"],
    jyutping: "bei2 loeng5 go3 ngo5",
    lesson: "给我两个（畀=给）",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 4,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-tai2-zo2-sin1",
    name: "睇咗先",
    phrase: "睇咗先",
    alternatives: ["睇咗先", "先看看"],
    jyutping: "tai2 zo2 sin1",
    lesson: "先看看再说（咗=了）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-hou2-dai2",
    name: "好抵",
    phrase: "好抵",
    alternatives: ["好抵", "很划算"],
    jyutping: "hou2 dai2",
    lesson: "很划算、值得",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-gu1-hung4",
    name: "孤寒",
    phrase: "孤寒",
    alternatives: ["孤寒", "吝啬"],
    jyutping: "gu1 hung4",
    lesson: "吝啬、小气",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-mou5-cin2",
    name: "冇钱",
    phrase: "冇钱",
    alternatives: ["冇钱", "冇錢", "没钱"],
    jyutping: "mou5 cin2",
    lesson: "没钱（口袋空空）",
    type: "guard",
    rarity: "basic",
    cost: 1,
    power: 5,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-dang2-zan6-sin1",
    name: "等阵先",
    phrase: "等阵先",
    alternatives: ["等阵先", "等陣先", "等一下"],
    jyutping: "dang2 zan6 sin1",
    lesson: "等一下再说",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-zau2-sin1-laa1",
    name: "走先啦",
    phrase: "走先啦",
    alternatives: ["走先啦", "我先走了"],
    jyutping: "zau2 sin1 laa1",
    lesson: "我先走了",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-heoi3-bin1-dou6",
    name: "去边度",
    phrase: "去边度",
    alternatives: ["去边度", "去哪裡", "去哪里"],
    jyutping: "heoi3 bin1 dou6",
    lesson: "去哪里（边度=哪里）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-ni1-dou6-hai6-bin1",
    name: "呢度系边",
    phrase: "呢度系边",
    alternatives: ["呢度系边", "這裡是哪", "这里是哪"],
    jyutping: "ni1 dou6 hai6 bin1",
    lesson: "这里是哪里",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-hai2-bin1-dou6",
    name: "喺边度",
    phrase: "喺边度",
    alternatives: ["喺边度", "在哪裡", "在哪里"],
    jyutping: "hai2 bin1 dou6",
    lesson: "在哪里（喺=在）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-sik1-m4-sik1-lou6",
    name: "识唔识路",
    phrase: "识唔识路",
    alternatives: ["识唔识路", "識唔識路", "认不认得路"],
    jyutping: "sik1 m4 sik1 lou6",
    lesson: "认不认得路（A唔AB 问句）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-dai3-ngo5-haang4",
    name: "带我行",
    phrase: "带我行",
    alternatives: ["带我行", "帶我走", "带我走"],
    jyutping: "dai3 ngo5 haang4",
    lesson: "带我走（行=走）",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 4,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-zik6-haang4-zyun3-zo2",
    name: "直行转左",
    phrase: "直行转左",
    alternatives: ["直行转左", "直行轉左", "直走左转"],
    jyutping: "zik6 haang4 zyun3 zo2",
    lesson: "直走然后左转",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-zau6-hai2-cin4-min6",
    name: "就喺前面",
    phrase: "就喺前面",
    alternatives: ["就喺前面", "就在前面"],
    jyutping: "zau6 hai2 cin4 min6",
    lesson: "就在前面",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-m4-goi1-ze3-ze3",
    name: "唔该借借",
    phrase: "唔该借借",
    alternatives: ["唔该借借", "唔該借借", "麻烦让让"],
    jyutping: "m4 goi1 ze3 ze3",
    lesson: "麻烦让一让（借借=让让）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-bang1-ngo5-sau2",
    name: "帮我手",
    phrase: "帮我手",
    alternatives: ["帮我手", "幫我手", "帮我一下"],
    jyutping: "bang1 ngo5 sau2",
    lesson: "帮我一把",
    type: "hybrid",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "造成 {power} 点伤害，并获得等量护甲。"
  },
  {
    id: "p17-gau3-ngo5",
    name: "救我",
    phrase: "救我",
    alternatives: ["救我"],
    jyutping: "gau3 ngo5",
    lesson: "救救我",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-siu2-sam1-di1",
    name: "小心啲",
    phrase: "小心啲",
    alternatives: ["小心啲", "小心点"],
    jyutping: "siu2 sam1 di1",
    lesson: "小心一点（啲=点）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-tai2-zyu6-keoi5",
    name: "睇住佢",
    phrase: "睇住佢",
    alternatives: ["睇住佢", "看着他"],
    jyutping: "tai2 zyu6 keoi5",
    lesson: "看着他（佢=他/她）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-jat1-saam1-ng5-cat1",
    name: "一三五七",
    phrase: "一三五七",
    alternatives: ["一三五七"],
    jyutping: "jat1 saam1 ng5 cat1",
    lesson: "单数一到七",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 3,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-ji6-sei3-luk6-baat3",
    name: "二四六八",
    phrase: "二四六八",
    alternatives: ["二四六八"],
    jyutping: "ji6 sei3 luk6 baat3",
    lesson: "双数二到八",
    type: "guard",
    rarity: "common",
    cost: 2,
    power: 16,
    description: "获得 {power} 点护甲，本回合抵挡来袭。"
  },
  {
    id: "p17-sap6-cyun4-sap6-mei6",
    name: "十全十美",
    phrase: "十全十美",
    alternatives: ["十全十美"],
    jyutping: "sap6 cyun4 sap6 mei6",
    lesson: "完美无缺",
    type: "heal",
    rarity: "rare",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-ji4-gaa1-gei2-dim2",
    name: "而家几点",
    phrase: "而家几点",
    alternatives: ["而家几点", "現在幾點", "现在几点"],
    jyutping: "ji4 gaa1 gei2 dim2",
    lesson: "现在几点（而家=现在）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-jat1-go3-zung1",
    name: "一个钟",
    phrase: "一个钟",
    alternatives: ["一个钟", "一個鐘", "一个小时"],
    jyutping: "jat1 go3 zung1",
    lesson: "一个小时（钟=小时）",
    type: "guard",
    rarity: "common",
    cost: 2,
    power: 20,
    description: "获得 {power} 点护甲，本回合抵挡来袭。"
  },
  {
    id: "p17-gam1-jat6-tin1-hei3",
    name: "今日天气",
    phrase: "今日天气",
    alternatives: ["今日天气", "今天天气"],
    jyutping: "gam1 jat6 tin1 hei3",
    lesson: "今天天气",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-ting1-jat6-gin3",
    name: "听日见",
    phrase: "听日见",
    alternatives: ["听日见", "聽日見", "明天见"],
    jyutping: "ting1 jat6 gin3",
    lesson: "明天见（听日=明天）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-ceot1-gaai1",
    name: "出街",
    phrase: "出街",
    alternatives: ["出街", "上街"],
    jyutping: "ceot1 gaai1",
    lesson: "上街、出门",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-maai5-je5",
    name: "买嘢",
    phrase: "买嘢",
    alternatives: ["买嘢", "買嘢", "买东西"],
    jyutping: "maai5 je5",
    lesson: "买东西（嘢=东西）",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 4,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-haang4-gaai1",
    name: "行街",
    phrase: "行街",
    alternatives: ["行街", "逛街"],
    jyutping: "haang4 gaai1",
    lesson: "逛街",
    type: "hybrid",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "造成 {power} 点伤害，并获得等量护甲。"
  },
  {
    id: "p17-bo1-lo4-baau1",
    name: "菠萝包",
    phrase: "菠萝包",
    alternatives: ["菠萝包", "菠蘿包"],
    jyutping: "bo1 lo4 baau1",
    lesson: "茶餐厅经典面包",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-daan6-taat1",
    name: "蛋挞",
    phrase: "蛋挞",
    alternatives: ["蛋挞", "蛋撻"],
    jyutping: "daan6 taat1",
    lesson: "酥皮点心（-t 入声尾）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-wan4-tan1-min6",
    name: "云吞面",
    phrase: "云吞面",
    alternatives: ["云吞面", "雲吞麵"],
    jyutping: "wan4 tan1 min6",
    lesson: "馄饨面",
    type: "hybrid",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "造成 {power} 点伤害，并获得等量护甲。"
  },
  {
    id: "p17-caa1-siu1",
    name: "叉烧",
    phrase: "叉烧",
    alternatives: ["叉烧", "叉燒"],
    jyutping: "caa1 siu1",
    lesson: "烤猪肉（蜜汁叉烧）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-bou1-tong1",
    name: "煲汤",
    phrase: "煲汤",
    alternatives: ["煲汤", "煲湯"],
    jyutping: "bou1 tong1",
    lesson: "广东人看家的老火汤",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-maai5-sung3",
    name: "买餸",
    phrase: "买餸",
    alternatives: ["买餸", "買餸", "买菜"],
    jyutping: "maai5 sung3",
    lesson: "买做菜的食材（餸=菜）",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 4,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-zyu2-faan6",
    name: "煮饭",
    phrase: "煮饭",
    alternatives: ["煮饭", "煮飯"],
    jyutping: "zyu2 faan6",
    lesson: "做饭",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-caau2-coi3",
    name: "炒菜",
    phrase: "炒菜",
    alternatives: ["炒菜"],
    jyutping: "caau2 coi3",
    lesson: "炒菜（锅气！）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-zing1-jyu4",
    name: "蒸鱼",
    phrase: "蒸鱼",
    alternatives: ["蒸鱼", "蒸魚"],
    jyutping: "zing1 jyu4",
    lesson: "清蒸鱼（粤菜功夫菜）",
    type: "attack",
    rarity: "rare",
    cost: 2,
    power: 11,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-cung1-loeng4",
    name: "冲凉",
    phrase: "冲凉",
    alternatives: ["冲凉", "沖涼", "洗澡"],
    jyutping: "cung1 loeng4",
    lesson: "洗澡",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-sai2-saam1",
    name: "洗衫",
    phrase: "洗衫",
    alternatives: ["洗衫", "洗衣服"],
    jyutping: "sai2 saam1",
    lesson: "洗衣服（衫=衣服）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-tou5-ngo6",
    name: "肚饿",
    phrase: "肚饿",
    alternatives: ["肚饿", "肚餓", "肚子饿"],
    jyutping: "tou5 ngo6",
    lesson: "肚子饿",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-sik6-zou5-caan1",
    name: "食早餐",
    phrase: "食早餐",
    alternatives: ["食早餐", "吃早餐"],
    jyutping: "sik6 zou5 caan1",
    lesson: "吃早餐",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-sik6-siu1-je6",
    name: "食宵夜",
    phrase: "食宵夜",
    alternatives: ["食宵夜", "吃夜宵"],
    jyutping: "sik6 siu1 je6",
    lesson: "吃夜宵",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-tai2-ji1-sang1",
    name: "睇医生",
    phrase: "睇医生",
    alternatives: ["睇医生", "看医生"],
    jyutping: "tai2 ji1 sang1",
    lesson: "看医生",
    type: "heal",
    rarity: "common",
    cost: 2,
    power: 11,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-sik6-joek6",
    name: "食药",
    phrase: "食药",
    alternatives: ["食药", "食藥", "吃药"],
    jyutping: "sik6 joek6",
    lesson: "吃药（-k 入声尾）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-tau4-wan4",
    name: "头晕",
    phrase: "头晕",
    alternatives: ["头晕", "頭暈"],
    jyutping: "tau4 wan4",
    lesson: "头晕",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-m4-hou2-geng1",
    name: "唔好惊",
    phrase: "唔好惊",
    alternatives: ["唔好惊", "唔好驚", "别害怕"],
    jyutping: "m4 hou2 geng1",
    lesson: "别害怕（惊=怕）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-m4-hou2-haam3",
    name: "唔好喊",
    phrase: "唔好喊",
    alternatives: ["唔好喊", "别哭"],
    jyutping: "m4 hou2 haam3",
    lesson: "别哭（喊=哭）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-joeng5-maa1",
    name: "养猫",
    phrase: "养猫",
    alternatives: ["养猫", "養貓"],
    jyutping: "joeng5 maa1",
    lesson: "养猫",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-gau2-zai2",
    name: "狗仔",
    phrase: "狗仔",
    alternatives: ["狗仔", "小狗"],
    jyutping: "gau2 zai2",
    lesson: "小狗（仔=小）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-jam2-naai5-caa4",
    name: "饮奶茶",
    phrase: "饮奶茶",
    alternatives: ["饮奶茶", "喝奶茶"],
    jyutping: "jam2 naai5 caa4",
    lesson: "喝奶茶（港式丝袜奶茶）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  }
];
