/**
 * P17 词海 · 幕2 扩容（雾海码头）：饮食茶楼 / 交通出行 / 天气昼夜 / 方位疑问。
 * 仅经 skillsFor 第五参 lexiconVersion=1 进入新战役卡池；旧局不可获取。
 * 粤拼为 LSHK 方案人工编写，待母语审校（P7 惯例）。
 */
import type { Skill } from "../../data";

export const P17_SKILLS_ACT2: Skill[] = [
  {
    id: "p17-sik6-faan6-mei6",
    name: "食饭未",
    phrase: "食饭未",
    alternatives: ["食饭未", "食飯未", "吃饭了吗"],
    jyutping: "sik6 faan6 mei6",
    lesson: "吃了吗（经典寒暄）",
    type: "hybrid",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "造成 {power} 点伤害，并获得等量护甲。"
  },
  {
    id: "p17-hou2-hou2-mei6",
    name: "好好味",
    phrase: "好好味",
    alternatives: ["好好味", "很好吃"],
    jyutping: "hou2 hou2 mei6",
    lesson: "非常好吃",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-hou2-baau2",
    name: "好饱",
    phrase: "好饱",
    alternatives: ["好饱", "好飽", "吃饱了"],
    jyutping: "hou2 baau2",
    lesson: "很饱",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-jam2-daam6-caa4",
    name: "饮啖茶",
    phrase: "饮啖茶",
    alternatives: ["饮啖茶", "飲啖茶", "喝口茶"],
    jyutping: "jam2 daam6 caa4",
    lesson: "喝口茶（啖=一口）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-jat1-zung1-loeng5-gin6",
    name: "一盅两件",
    phrase: "一盅两件",
    alternatives: ["一盅两件", "一盅兩件"],
    jyutping: "jat1 zung1 loeng5 gin6",
    lesson: "一壶茶两笼点心（饮茶标配）",
    type: "heal",
    rarity: "rare",
    cost: 2,
    power: 9,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-lok6-daan1",
    name: "落单",
    phrase: "落单",
    alternatives: ["落单", "落單", "点菜"],
    jyutping: "lok6 daan1",
    lesson: "点单、下单",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-daa2-baau1",
    name: "打包",
    phrase: "打包",
    alternatives: ["打包"],
    jyutping: "daa2 baau1",
    lesson: "剩菜带走",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-jam2-sing3",
    name: "饮胜",
    phrase: "饮胜",
    alternatives: ["饮胜", "飲勝", "干杯"],
    jyutping: "jam2 sing3",
    lesson: "干杯",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-hou2-zeng3",
    name: "好正",
    phrase: "好正",
    alternatives: ["好正", "太棒了"],
    jyutping: "hou2 zeng3",
    lesson: "太棒了",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-hou2-daam6",
    name: "好淡",
    phrase: "好淡",
    alternatives: ["好淡", "味道太淡"],
    jyutping: "hou2 daam6",
    lesson: "味道太淡",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-hou2-haam4",
    name: "好咸",
    phrase: "好咸",
    alternatives: ["好咸", "好鹹", "太咸了"],
    jyutping: "hou2 haam4",
    lesson: "太咸了",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-gaa1-do1-wun2-faan6",
    name: "加多碗饭",
    phrase: "加多碗饭",
    alternatives: ["加多碗饭", "加多碗飯", "再加一碗饭"],
    jyutping: "gaa1 do1 wun2 faan6",
    lesson: "再加一碗饭",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 4,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-m4-jiu3-laat6",
    name: "唔要辣",
    phrase: "唔要辣",
    alternatives: ["唔要辣", "不要辣"],
    jyutping: "m4 jiu3 laat6",
    lesson: "不要辣",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-sik6-zo2-baau2",
    name: "食饱咗",
    phrase: "食饱咗",
    alternatives: ["食饱咗", "食飽咗", "吃饱了"],
    jyutping: "sik6 zo2 baau2",
    lesson: "吃饱了",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-ceng2-nei5-sik6-faan6",
    name: "请你食饭",
    phrase: "请你食饭",
    alternatives: ["请你食饭", "請你食飯", "请你吃饭"],
    jyutping: "ceng2 nei5 sik6 faan6",
    lesson: "请你吃饭（我买单）",
    type: "heal",
    rarity: "rare",
    cost: 2,
    power: 10,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-jau5-mou5-wai2",
    name: "有冇位",
    phrase: "有冇位",
    alternatives: ["有冇位", "有没有位子"],
    jyutping: "jau5 mou5 wai2",
    lesson: "有没有位子",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-daap3-dik1-si2",
    name: "搭的士",
    phrase: "搭的士",
    alternatives: ["搭的士", "打出租车"],
    jyutping: "daap3 dik1 si2",
    lesson: "坐出租车",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-heoi3-dou3-bin1",
    name: "去到边",
    phrase: "去到边",
    alternatives: ["去到边", "去到哪"],
    jyutping: "heoi3 dou3 bin1",
    lesson: "到哪里了",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-lok6-ce1",
    name: "落车",
    phrase: "落车",
    alternatives: ["落车", "落車", "下车"],
    jyutping: "lok6 ce1",
    lesson: "下车",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-zyun3-zo2-zyun3-jau6",
    name: "转左转右",
    phrase: "转左转右",
    alternatives: ["转左转右", "轉左轉右"],
    jyutping: "zyun3 zo2 zyun3 jau6",
    lesson: "左转右转（绕路）",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 3,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-m4-goi1-ting4-ce1",
    name: "唔该停车",
    phrase: "唔该停车",
    alternatives: ["唔该停车", "唔該停車", "麻烦停车"],
    jyutping: "m4 goi1 ting4 ce1",
    lesson: "麻烦停一下车",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-gei2-hou6-ce1",
    name: "几号车",
    phrase: "几号车",
    alternatives: ["几号车", "幾號車"],
    jyutping: "gei2 hou6 ce1",
    lesson: "几号车（几路公交）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-hoi1-ce1-laa1",
    name: "开车啦",
    phrase: "开车啦",
    alternatives: ["开车啦", "開車啦", "开车吧"],
    jyutping: "hoi1 ce1 laa1",
    lesson: "开车吧、出发",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-maan6-maan6-haang4",
    name: "慢慢行",
    phrase: "慢慢行",
    alternatives: ["慢慢行", "慢走"],
    jyutping: "maan6 maan6 haang4",
    lesson: "慢走（送别客气话）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-haang4-faai3-loeng5-bou6",
    name: "行快两步",
    phrase: "行快两步",
    alternatives: ["行快两步", "走快兩步", "走快一点"],
    jyutping: "haang4 faai3 loeng5 bou6",
    lesson: "走快两步",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 4,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-co5-dai1-sin1",
    name: "坐低先",
    phrase: "坐低先",
    alternatives: ["坐低先", "先坐下"],
    jyutping: "co5 dai1 sin1",
    lesson: "先坐下",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-dou3-zaam6-mei6-jau5",
    name: "到站未有",
    phrase: "到站未有",
    alternatives: ["到站未有", "到站了吗"],
    jyutping: "dou3 zaam6 mei6 jau5",
    lesson: "到站了没有",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-lok6-jyu5-aa3",
    name: "落雨啊",
    phrase: "落雨啊",
    alternatives: ["落雨啊", "下雨了"],
    jyutping: "lok6 jyu5 aa3",
    lesson: "下雨了",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-daa2-fung1",
    name: "打风",
    phrase: "打风",
    alternatives: ["打风", "打風", "刮台风"],
    jyutping: "daa2 fung1",
    lesson: "刮台风",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-hou2-dung3",
    name: "好冻",
    phrase: "好冻",
    alternatives: ["好冻", "好凍", "好冷"],
    jyutping: "hou2 dung3",
    lesson: "很冷",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-hou2-jit6",
    name: "好热",
    phrase: "好热",
    alternatives: ["好热", "好熱"],
    jyutping: "hou2 jit6",
    lesson: "很热",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-ceot1-taai3-joeng4",
    name: "出太阳",
    phrase: "出太阳",
    alternatives: ["出太阳", "出太陽"],
    jyutping: "ceot1 taai3 joeng4",
    lesson: "出太阳了",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-hou2-tin1",
    name: "好天",
    phrase: "好天",
    alternatives: ["好天", "天气好"],
    jyutping: "hou2 tin1",
    lesson: "天气好",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-ngaan3-zau3",
    name: "晏昼",
    phrase: "晏昼",
    alternatives: ["晏昼", "晏晝", "中午"],
    jyutping: "ngaan3 zau3",
    lesson: "中午（古音留存词）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-gam1-maan5",
    name: "今晚",
    phrase: "今晚",
    alternatives: ["今晚"],
    jyutping: "gam1 maan5",
    lesson: "今晚",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-je6-maan5",
    name: "夜晚",
    phrase: "夜晚",
    alternatives: ["夜晚"],
    jyutping: "je6 maan5",
    lesson: "夜晚",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-uk1-kei2",
    name: "屋企",
    phrase: "屋企",
    alternatives: ["屋企", "家"],
    jyutping: "uk1 kei2",
    lesson: "家",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-faan1-uk1-kei2",
    name: "返屋企",
    phrase: "返屋企",
    alternatives: ["返屋企", "回家"],
    jyutping: "faan1 uk1 kei2",
    lesson: "回家",
    type: "heal",
    rarity: "common",
    cost: 2,
    power: 9,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-heoi3-co3-so2",
    name: "去厕所",
    phrase: "去厕所",
    alternatives: ["去厕所", "去廁所"],
    jyutping: "heoi3 co3 so2",
    lesson: "去洗手间",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-bin1-go3",
    name: "边个",
    phrase: "边个",
    alternatives: ["边个", "邊個", "谁"],
    jyutping: "bin1 go3",
    lesson: "谁",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-mat1-je5",
    name: "乜嘢",
    phrase: "乜嘢",
    alternatives: ["乜嘢", "什么"],
    jyutping: "mat1 je5",
    lesson: "什么",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-dim2-joeng2",
    name: "点样",
    phrase: "点样",
    alternatives: ["点样", "點樣", "怎么样"],
    jyutping: "dim2 joeng2",
    lesson: "怎么样",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-gei2-si2",
    name: "几时",
    phrase: "几时",
    alternatives: ["几时", "幾時", "什么时候"],
    jyutping: "gei2 si2",
    lesson: "什么时候",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-jat1-baak3-man1",
    name: "一百蚊",
    phrase: "一百蚊",
    alternatives: ["一百蚊", "一百块钱"],
    jyutping: "jat1 baak3 man1",
    lesson: "一百块钱（蚊=元）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-loeng5-baak3-man1",
    name: "两百蚊",
    phrase: "两百蚊",
    alternatives: ["两百蚊", "兩百蚊", "两百块钱"],
    jyutping: "loeng5 baak3 man1",
    lesson: "两百块钱",
    type: "guard",
    rarity: "common",
    cost: 2,
    power: 18,
    description: "获得 {power} 点护甲，本回合抵挡来袭。"
  },
  {
    id: "p17-saam1-cin2-man1",
    name: "三千蚊",
    phrase: "三千蚊",
    alternatives: ["三千蚊", "三千块钱"],
    jyutping: "saam1 cin2 man1",
    lesson: "三千块钱",
    type: "guard",
    rarity: "rare",
    cost: 2,
    power: 20,
    description: "获得 {power} 点护甲，本回合抵挡来袭。"
  },
  {
    id: "p17-mou5-je5",
    name: "冇嘢",
    phrase: "冇嘢",
    alternatives: ["冇嘢", "没事"],
    jyutping: "mou5 je5",
    lesson: "没事",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-jau5-je5",
    name: "有事",
    phrase: "有事",
    alternatives: ["有事", "出事了"],
    jyutping: "jau5 je5",
    lesson: "有事、出事了",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-hou2-sik6",
    name: "好食",
    phrase: "好食",
    alternatives: ["好食", "好吃"],
    jyutping: "hou2 sik6",
    lesson: "好吃",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-jam2-seoi2",
    name: "饮水",
    phrase: "饮水",
    alternatives: ["饮水", "飲水", "喝水"],
    jyutping: "jam2 seoi2",
    lesson: "喝水",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-faan1-loi4",
    name: "返来",
    phrase: "返来",
    alternatives: ["返来", "返來", "回来"],
    jyutping: "faan1 loi4",
    lesson: "回来",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-heoi3-waan2",
    name: "去玩",
    phrase: "去玩",
    alternatives: ["去玩"],
    jyutping: "heoi3 waan2",
    lesson: "出去玩",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-daap3-dei6-tit3",
    name: "搭地铁",
    phrase: "搭地铁",
    alternatives: ["搭地铁", "坐地铁"],
    jyutping: "daap3 dei6 tit3",
    lesson: "坐地铁（-t 入声尾）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-daap3-baa1-si2",
    name: "搭巴士",
    phrase: "搭巴士",
    alternatives: ["搭巴士", "坐公交"],
    jyutping: "daap3 baa1 si2",
    lesson: "坐公交车（巴士=bus）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-caai2-daan1-ce1",
    name: "踩单车",
    phrase: "踩单车",
    alternatives: ["踩单车", "騎自行車", "骑自行车"],
    jyutping: "caai2 daan1 ce1",
    lesson: "骑自行车（踩=骑）",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 4,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-daap3-syun4",
    name: "搭船",
    phrase: "搭船",
    alternatives: ["搭船", "坐船"],
    jyutping: "daap3 syun4",
    lesson: "坐船（渡轮）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-maai5-fei1",
    name: "买飞",
    phrase: "买飞",
    alternatives: ["买飞", "買飛", "买票"],
    jyutping: "maai5 fei1",
    lesson: "买票（飞=fare 音译）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-paai4-deoi2",
    name: "排队",
    phrase: "排队",
    alternatives: ["排队", "排隊"],
    jyutping: "paai4 deoi2",
    lesson: "排队",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-sak1-ce1",
    name: "塞车",
    phrase: "塞车",
    alternatives: ["塞车", "塞車", "堵车"],
    jyutping: "sak1 ce1",
    lesson: "堵车（-k 入声尾）",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-hung4-luk6-dang1",
    name: "红绿灯",
    phrase: "红绿灯",
    alternatives: ["红绿灯", "紅綠燈"],
    jyutping: "hung4 luk6 dang1",
    lesson: "红绿灯（三个入声字连发）",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 3,
    hits: 3,
    description: "连续攻击 3 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-tin1-kiu4",
    name: "天桥",
    phrase: "天桥",
    alternatives: ["天桥", "天橋"],
    jyutping: "tin1 kiu4",
    lesson: "人行天桥",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-gwaa3-zyu6-nei5",
    name: "挂住你",
    phrase: "挂住你",
    alternatives: ["挂住你", "掛住你", "想着你"],
    jyutping: "gwaa3 zyu6 nei5",
    lesson: "惦记着你（挂住=想念）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-mong4-dou3-din1",
    name: "忙到癫",
    phrase: "忙到癫",
    alternatives: ["忙到癫", "忙到瘋", "忙疯了"],
    jyutping: "mong4 dou3 din1",
    lesson: "忙疯了（癫=疯）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-dak1-haan4",
    name: "得闲",
    phrase: "得闲",
    alternatives: ["得闲", "得閒", "有空"],
    jyutping: "dak1 haan4",
    lesson: "有空（得闲饮茶=有空喝茶）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-gon2-si4-gaan3",
    name: "赶时间",
    phrase: "赶时间",
    alternatives: ["赶时间", "趕時間"],
    jyutping: "gon2 si4 gaan3",
    lesson: "赶时间",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-zou2-zou2",
    name: "朝早",
    phrase: "朝早",
    alternatives: ["朝早", "早上"],
    jyutping: "zou2 zou2",
    lesson: "早上（朝=早晨）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-hau6-jat6",
    name: "后日",
    phrase: "后日",
    alternatives: ["后日", "後日", "后天"],
    jyutping: "hau6 jat6",
    lesson: "后天",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-cin4-jat6",
    name: "前日",
    phrase: "前日",
    alternatives: ["前日", "前天"],
    jyutping: "cin4 jat6",
    lesson: "前天",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-haa6-zau3",
    name: "下昼",
    phrase: "下昼",
    alternatives: ["下昼", "下晝", "下午"],
    jyutping: "haa6 zau3",
    lesson: "下午（与晏昼相对）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-fong3-gung1",
    name: "放工",
    phrase: "放工",
    alternatives: ["放工", "下班"],
    jyutping: "fong3 gung1",
    lesson: "下班（与返工相对）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-ze2-gaau2",
    name: "借钱",
    phrase: "借钱",
    alternatives: ["借钱", "借錢"],
    jyutping: "ze3 cin2",
    lesson: "借钱（借=ze3，与「借借」同字）",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-wan2-caan1",
    name: "搵食",
    phrase: "搵食",
    alternatives: ["搵食", "谋生"],
    jyutping: "wan2 sik6",
    lesson: "谋生（搵=找）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-uk1-kei2-man6",
    name: "返屋企问下",
    phrase: "返屋企问下",
    alternatives: ["返屋企问下", "回家问问"],
    jyutping: "faan1 uk1 kei2 man6 haa5",
    lesson: "回家问一下（问下=问问）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-dim2-syun2",
    name: "点算",
    phrase: "点算",
    alternatives: ["点算", "怎么办"],
    jyutping: "dim2 syun3",
    lesson: "怎么办（点算=如何是好）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  }
];
