/**
 * P17 词海 · 幕3 扩容（云顶声窟）：情绪感受 / 鼓励俗语 / 沟通用语 / 成语收束。
 * 仅经 skillsFor 第五参 lexiconVersion=1 进入新战役卡池；旧局不可获取。
 * 粤拼为 LSHK 方案人工编写，待母语审校（P7 惯例）。
 */
import type { Skill } from "../../data";

export const P17_SKILLS_ACT3: Skill[] = [
  {
    id: "p17-hou2-hoi1-sam1",
    name: "好开心",
    phrase: "好开心",
    alternatives: ["好开心", "好開心", "很高兴"],
    jyutping: "hou2 hoi1 sam1",
    lesson: "很开心",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-m4-hoi1-sam1",
    name: "唔开心",
    phrase: "唔开心",
    alternatives: ["唔开心", "唔開心", "不开心"],
    jyutping: "m4 hoi1 sam1",
    lesson: "不开心",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-hou2-nau2",
    name: "好嬲",
    phrase: "好嬲",
    alternatives: ["好嬲", "很生气"],
    jyutping: "hou2 nau2",
    lesson: "很生气",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-hou2-gui6",
    name: "好攰",
    phrase: "好攰",
    alternatives: ["好攰", "好累"],
    jyutping: "hou2 gui6",
    lesson: "很累",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-fan3-gaau3",
    name: "瞓觉",
    phrase: "瞓觉",
    alternatives: ["瞓觉", "瞓覺", "睡觉"],
    jyutping: "fan3 gaau3",
    lesson: "睡觉",
    type: "heal",
    rarity: "common",
    cost: 2,
    power: 11,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-hei2-san1",
    name: "起身",
    phrase: "起身",
    alternatives: ["起身", "起床"],
    jyutping: "hei2 san1",
    lesson: "起床",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-fong3-gaa3",
    name: "放假",
    phrase: "放假",
    alternatives: ["放假"],
    jyutping: "fong3 gaa3",
    lesson: "放假",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-faan1-gung1",
    name: "返工",
    phrase: "返工",
    alternatives: ["返工", "上班"],
    jyutping: "faan1 gung1",
    lesson: "上班",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-gaa1-jau2",
    name: "加油",
    phrase: "加油",
    alternatives: ["加油"],
    jyutping: "gaa1 jau2",
    lesson: "打气鼓励",
    type: "strength",
    rarity: "common",
    cost: 1,
    power: 2,
    description: "本场战斗获得 {power} 点声势，之后攻击更强。"
  },
  {
    id: "p17-bei2-sam1-gei1",
    name: "畀心机",
    phrase: "畀心机",
    alternatives: ["畀心机", "用心点"],
    jyutping: "bei2 sam1 gei1",
    lesson: "用心努力",
    type: "strength",
    rarity: "common",
    cost: 1,
    power: 3,
    description: "本场战斗获得 {power} 点声势，之后攻击更强。"
  },
  {
    id: "p17-hou2-lek1",
    name: "好叻",
    phrase: "好叻",
    alternatives: ["好叻", "真聪明"],
    jyutping: "hou2 lek1",
    lesson: "真聪明、真棒",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-leng3-neoi2",
    name: "靓女",
    phrase: "靓女",
    alternatives: ["靓女", "靚女", "美女"],
    jyutping: "leng3 neoi2",
    lesson: "美女（称呼）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-leng3-zai2",
    name: "靓仔",
    phrase: "靓仔",
    alternatives: ["靓仔", "靚仔", "帅哥"],
    jyutping: "leng3 zai2",
    lesson: "帅哥（称呼）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-king1-gai2",
    name: "倾偈",
    phrase: "倾偈",
    alternatives: ["倾偈", "傾偈", "聊天"],
    jyutping: "king1 gai2",
    lesson: "聊天",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-gong2-gu2",
    name: "讲古",
    phrase: "讲古",
    alternatives: ["讲古", "講古", "讲故事"],
    jyutping: "gong2 gu2",
    lesson: "讲故事",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-sau1-fung1",
    name: "收风",
    phrase: "收风",
    alternatives: ["收风", "收風", "打听消息"],
    jyutping: "sau1 fung1",
    lesson: "打听消息",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-sap1-sap1-seoi3",
    name: "湿湿碎",
    phrase: "湿湿碎",
    alternatives: ["湿湿碎", "濕濕碎", "小意思"],
    jyutping: "sap1 sap1 seoi3",
    lesson: "小意思、不值一提",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-si6-daan6-laa1",
    name: "是但啦",
    phrase: "是但啦",
    alternatives: ["是但啦", "随便啦"],
    jyutping: "si6 daan6 laa1",
    lesson: "随便啦",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-kau4-kei4-laa1",
    name: "求其啦",
    phrase: "求其啦",
    alternatives: ["求其啦", "随便应付"],
    jyutping: "kau4 kei4 laa1",
    lesson: "马马虎虎、随便",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-leon6-zeon6",
    name: "论尽",
    phrase: "论尽",
    alternatives: ["论尽", "論盡", "笨手笨脚"],
    jyutping: "leon6 zeon6",
    lesson: "笨手笨脚",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-m4-hou2-gam2",
    name: "唔好噉",
    phrase: "唔好噉",
    alternatives: ["唔好噉", "别这样"],
    jyutping: "m4 hou2 gam2",
    lesson: "别这样",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-mai5-zyu6-sin1",
    name: "咪住先",
    phrase: "咪住先",
    alternatives: ["咪住先", "先等等"],
    jyutping: "mai5 zyu6 sin1",
    lesson: "先等等（咪=别）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-ting4-dai1",
    name: "停低",
    phrase: "停低",
    alternatives: ["停低", "停下来"],
    jyutping: "ting4 dai1",
    lesson: "停下来",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-ngo5-sam2-haa5",
    name: "我谂下",
    phrase: "我谂下",
    alternatives: ["我谂下", "我諗下", "我想想"],
    jyutping: "ngo5 sam2 haa5",
    lesson: "我想想（谂=想）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-nei5-waa6-ne1",
    name: "你话呢",
    phrase: "你话呢",
    alternatives: ["你话呢", "你話呢", "你说呢"],
    jyutping: "nei5 waa6 ne1",
    lesson: "你说呢",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-m4-zi1",
    name: "唔知",
    phrase: "唔知",
    alternatives: ["唔知", "不知道"],
    jyutping: "m4 zi1",
    lesson: "不知道",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-zi1-dou3-laa1",
    name: "知道啦",
    phrase: "知道啦",
    alternatives: ["知道啦", "知道了"],
    jyutping: "zi1 dou3 laa1",
    lesson: "知道了（略不耐烦）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-ming4-baak6",
    name: "明白",
    phrase: "明白",
    alternatives: ["明白", "明白了"],
    jyutping: "ming4 baak6",
    lesson: "明白了",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-m4-ming4-baak6",
    name: "唔明白",
    phrase: "唔明白",
    alternatives: ["唔明白", "不明白"],
    jyutping: "m4 ming4 baak6",
    lesson: "不明白",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-zoi3-gong2-jat1-ci3",
    name: "再讲一次",
    phrase: "再讲一次",
    alternatives: ["再讲一次", "再講一次", "再说一遍"],
    jyutping: "zoi3 gong2 jat1 ci3",
    lesson: "再说一遍",
    type: "multi",
    rarity: "common",
    cost: 1,
    power: 3,
    hits: 2,
    description: "连续攻击 2 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-gong2-maan6-di1",
    name: "讲慢啲",
    phrase: "讲慢啲",
    alternatives: ["讲慢啲", "講慢啲", "说慢点"],
    jyutping: "gong2 maan6 di1",
    lesson: "说慢一点",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-hou2-ging6",
    name: "好劲",
    phrase: "好劲",
    alternatives: ["好劲", "好勁", "好厉害"],
    jyutping: "hou2 ging6",
    lesson: "好厉害",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-mou5-ngaan5-tai2",
    name: "冇眼睇",
    phrase: "冇眼睇",
    alternatives: ["冇眼睇", "看不下去"],
    jyutping: "mou5 ngaan5 tai2",
    lesson: "看不下去、不忍直视",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-sam1-sap1",
    name: "心噏",
    phrase: "心噏",
    alternatives: ["心噏", "心里憋闷"],
    jyutping: "sam1 sap1",
    lesson: "心里憋闷",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-syu1-fuk6",
    name: "舒服",
    phrase: "舒服",
    alternatives: ["舒服"],
    jyutping: "syu1 fuk6",
    lesson: "舒服",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-beng6-zo2",
    name: "病咗",
    phrase: "病咗",
    alternatives: ["病咗", "病了"],
    jyutping: "beng6 zo2",
    lesson: "生病了",
    type: "heal",
    rarity: "common",
    cost: 2,
    power: 9,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-jam2-bui1-jit6-caa4",
    name: "饮杯热茶",
    phrase: "饮杯热茶",
    alternatives: ["饮杯热茶", "飲杯熱茶", "喝杯热茶"],
    jyutping: "jam2 bui1 jit6 caa4",
    lesson: "喝杯热茶（定惊）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-zou2-di1-tau2",
    name: "早啲唞",
    phrase: "早啲唞",
    alternatives: ["早啲唞", "早点休息"],
    jyutping: "zou2 di1 tau2",
    lesson: "早点休息（唞=休息）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-m4-hou2-je6",
    name: "唔好夜",
    phrase: "唔好夜",
    alternatives: ["唔好夜", "别太晚"],
    jyutping: "m4 hou2 je6",
    lesson: "别搞太晚",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-jat1-jyu1-heoi3",
    name: "一于去",
    phrase: "一于去",
    alternatives: ["一于去", "一於去", "干脆去"],
    jyutping: "jat1 jyu1 heoi3",
    lesson: "干脆去、就这么去",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 10,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-gong2-do1-mou4-wai6",
    name: "讲多无谓",
    phrase: "讲多无谓",
    alternatives: ["讲多无谓", "講多無謂", "多说无益"],
    jyutping: "gong2 do1 mou4 wai6",
    lesson: "多说无益",
    type: "attack",
    rarity: "rare",
    cost: 2,
    power: 11,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-jat1-jyu1-gam2-waa6",
    name: "一于咁话",
    phrase: "一于咁话",
    alternatives: ["一于咁话", "一於咁話", "就这么定了"],
    jyutping: "jat1 jyu1 gam2 waa6",
    lesson: "就这么定了",
    type: "guard",
    rarity: "rare",
    cost: 2,
    power: 12,
    description: "获得 {power} 点护甲，本回合抵挡来袭。"
  },
  {
    id: "p17-siu3-sei2-ngo5",
    name: "笑死我",
    phrase: "笑死我",
    alternatives: ["笑死我", "笑死我了"],
    jyutping: "siu3 sei2 ngo5",
    lesson: "笑死我了",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-maan6-gung1-ceot1-sai3-fo3",
    name: "慢工出细货",
    phrase: "慢工出细货",
    alternatives: ["慢工出细货", "慢工出細貨", "慢工出细活"],
    jyutping: "maan6 gung1 ceot1 sai3 fo3",
    lesson: "慢工出细活",
    type: "strength",
    rarity: "rare",
    cost: 1,
    power: 3,
    description: "本场战斗获得 {power} 点声势，之后攻击更强。"
  },
  {
    id: "p17-faai3-dou1-zaam2-lyun6-maa4",
    name: "快刀斩乱麻",
    phrase: "快刀斩乱麻",
    alternatives: ["快刀斩乱麻", "快刀斬亂麻"],
    jyutping: "faai3 dou1 zaam2 lyun6 maa4",
    lesson: "快刀斩乱麻（果断解决）",
    type: "multi",
    rarity: "rare",
    cost: 2,
    power: 5,
    hits: 3,
    description: "连续攻击 3 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-jat1-hei3-ho1-sing4",
    name: "一气呵成",
    phrase: "一气呵成",
    alternatives: ["一气呵成", "一氣呵成"],
    jyutping: "jat1 hei3 ho1 sing4",
    lesson: "一口气完成",
    type: "multi",
    rarity: "rare",
    cost: 2,
    power: 5,
    hits: 3,
    description: "连续攻击 3 次，每次造成 {power} 点伤害。"
  },
  {
    id: "p17-sam1-dou1-hon4-maai4",
    name: "心都寒埋",
    phrase: "心都寒埋",
    alternatives: ["心都寒埋", "心都凉了"],
    jyutping: "sam1 dou1 hon4 maai4",
    lesson: "心都凉了（埋=彻底）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-m4-hou2-ji3-si1-daa2-gaau2",
    name: "唔好意思打搅",
    phrase: "唔好意思打搅",
    alternatives: ["唔好意思打搅", "不好意思打扰"],
    jyutping: "m4 hou2 ji3 si1 daa2 gaau2",
    lesson: "不好意思打扰",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-duk6-jat1-mou4-ji6",
    name: "独一无二",
    phrase: "独一无二",
    alternatives: ["独一无二", "獨一無二"],
    jyutping: "duk6 jat1 mou4 ji6",
    lesson: "独一无二",
    type: "attack",
    rarity: "rare",
    cost: 2,
    power: 12,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-wan2-zan6",
    name: "稳阵",
    phrase: "稳阵",
    alternatives: ["稳阵", "穩陣", "稳妥"],
    jyutping: "wan2 zan6",
    lesson: "稳妥、靠得住",
    type: "guard",
    rarity: "common",
    cost: 2,
    power: 18,
    description: "获得 {power} 点护甲，本回合抵挡来袭。"
  },
  {
    id: "p17-hou2-seng1-hou2-hei3",
    name: "好声好气",
    phrase: "好声好气",
    alternatives: ["好声好气", "好聲好氣", "心平气和"],
    jyutping: "hou2 seng1 hou2 hei3",
    lesson: "心平气和地说话",
    type: "guard",
    rarity: "rare",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-sam1-jyun5",
    name: "心软",
    phrase: "心软",
    alternatives: ["心软", "心軟"],
    jyutping: "sam1 jyun5",
    lesson: "心软（软=soft）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-gik1-hei3",
    name: "激气",
    phrase: "激气",
    alternatives: ["激气", "激氣", "气人"],
    jyutping: "gik1 hei3",
    lesson: "令人生气、憋气（-k 入声）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-nau2-dou3-baau3",
    name: "嬲到爆",
    phrase: "嬲到爆",
    alternatives: ["嬲到爆", "气爆了"],
    jyutping: "nau2 dou3 baau3",
    lesson: "气炸了（爆=程度爆表）",
    type: "attack",
    rarity: "rare",
    cost: 2,
    power: 12,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-hou2-mun6",
    name: "好闷",
    phrase: "好闷",
    alternatives: ["好闷", "好悶", "好无聊"],
    jyutping: "hou2 mun6",
    lesson: "好无聊（闷=bored）",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-m4-zai3",
    name: "唔制",
    phrase: "唔制",
    alternatives: ["唔制", "不干"],
    jyutping: "m4 zai3",
    lesson: "不干、不愿意（撒娇式拒绝）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-sing2-muk6",
    name: "醒目",
    phrase: "醒目",
    alternatives: ["醒目", "机灵"],
    jyutping: "sing2 muk6",
    lesson: "机灵、反应快（-k 入声）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-sai3-seng1",
    name: "细声啲",
    phrase: "细声啲",
    alternatives: ["细声啲", "小声点"],
    jyutping: "sai3 seng1 di1",
    lesson: "小声点（细=小）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 7,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-m4-hou2-cou4",
    name: "唔好嘈",
    phrase: "唔好嘈",
    alternatives: ["唔好嘈", "别吵"],
    jyutping: "m4 hou2 cou4",
    lesson: "别吵（嘈=吵闹）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-gong2-zan1",
    name: "讲真",
    phrase: "讲真",
    alternatives: ["讲真", "講真", "说实话"],
    jyutping: "gong2 zan1",
    lesson: "说实话（口头禅）",
    type: "attack",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "造成 {power} 点伤害。"
  },
  {
    id: "p17-gong2-daai6-waa6",
    name: "讲大话",
    phrase: "讲大话",
    alternatives: ["讲大话", "撒谎"],
    jyutping: "gong2 daai6 waa6",
    lesson: "撒谎（大话=谎话）",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-ngaak1-jan4",
    name: "呃人",
    phrase: "呃人",
    alternatives: ["呃人", "骗人"],
    jyutping: "ngaak1 jan4",
    lesson: "骗人（-k 入声尾）",
    type: "weaken",
    rarity: "common",
    cost: 1,
    power: 5,
    description: "造成 {power} 点伤害，并令敌人虚弱 2 回合。"
  },
  {
    id: "p17-gong2-siu3",
    name: "讲笑",
    phrase: "讲笑",
    alternatives: ["讲笑", "开玩笑"],
    jyutping: "gong2 siu3",
    lesson: "开玩笑（讲笑咋=开玩笑的）",
    type: "tempo",
    rarity: "common",
    cost: 1,
    power: 6,
    description: "获得 {power} 点护甲，并重新抽取一组手牌。"
  },
  {
    id: "p17-jing6-zan1",
    name: "认真",
    phrase: "认真",
    alternatives: ["认真", "認真"],
    jyutping: "jing6 zan1",
    lesson: "认真（唔系讲笑）",
    type: "strength",
    rarity: "common",
    cost: 1,
    power: 3,
    description: "本场战斗获得 {power} 点声势，之后攻击更强。"
  },
  {
    id: "p17-bou2-zung6",
    name: "保重",
    phrase: "保重",
    alternatives: ["保重"],
    jyutping: "bou2 zung6",
    lesson: "保重（送别叮嘱）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-san1-tai2-gin6-hong1",
    name: "身体健康",
    phrase: "身体健康",
    alternatives: ["身体健康"],
    jyutping: "san1 tai2 gin6 hong1",
    lesson: "身体健康（祝福语）",
    type: "heal",
    rarity: "rare",
    cost: 2,
    power: 11,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-gung1-hei2-faat3-coi4",
    name: "恭喜发财",
    phrase: "恭喜发财",
    alternatives: ["恭喜发财", "恭喜發財"],
    jyutping: "gung1 hei2 faat3 coi4",
    lesson: "恭喜发财（faat3 -t 入声）",
    type: "heal",
    rarity: "rare",
    cost: 2,
    power: 10,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-san1-nin4-faai3-lok6",
    name: "新年快乐",
    phrase: "新年快乐",
    alternatives: ["新年快乐", "新年快樂"],
    jyutping: "san1 nin4 faai3 lok6",
    lesson: "新年快乐（lok6 -k 入声）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-saang1-jat6-faai3-lok6",
    name: "生日快乐",
    phrase: "生日快乐",
    alternatives: ["生日快乐", "生日快樂"],
    jyutping: "saang1 jat6 faai3 lok6",
    lesson: "生日快乐",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  },
  {
    id: "p17-maan6-si6-jyu4-ji3",
    name: "万事如意",
    phrase: "万事如意",
    alternatives: ["万事如意", "萬事如意"],
    jyutping: "maan6 si6 jyu4 ji3",
    lesson: "万事如意（祝福语）",
    type: "guard",
    rarity: "rare",
    cost: 2,
    power: 14,
    description: "获得 {power} 点护甲，本回合抵挡来袭。"
  },
  {
    id: "p17-siu1-siu1-hei3",
    name: "消消气",
    phrase: "消消气",
    alternatives: ["消消气"],
    jyutping: "siu1 siu1 hei3",
    lesson: "消消气（劝架用语）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-m4-gwan2-si6",
    name: "唔紧要嘅",
    phrase: "唔紧要嘅",
    alternatives: ["唔紧要嘅", "没关系的"],
    jyutping: "m4 gan2 jiu3 ge3",
    lesson: "没关系的（嘅句尾软化）",
    type: "guard",
    rarity: "common",
    cost: 1,
    power: 9,
    description: "获得 {power} 点护甲。"
  },
  {
    id: "p17-zung1-ji3-nei5",
    name: "中意你",
    phrase: "中意你",
    alternatives: ["中意你", "喜欢你"],
    jyutping: "zung1 ji3 nei5",
    lesson: "喜欢你（中意=喜欢）",
    type: "heal",
    rarity: "common",
    cost: 1,
    power: 8,
    description: "回复 {power} 点生命。"
  }
];
